repository_type: pipeline

nf_core_version: 3.1.1

lint: {}

template:
  org: nf-core
  name: varcall
  description: Nextflow pipeline for variant calling
  author: Srikanth Srinivas
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
